### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ashvala** [Ashvala/Jie#1]
#### For Feb 25th 2015.
- [x] fix visuals
- [x] figure out a more coherent bridge.js mechanism
- [x] figure out how to make things more useful with node.js
- [ ] sequencers
#### Bonus:
- [x] work visuals out for iOS
