### ISSUE TITLE
TODO for Feb 28th

### ISSUE THREAD

**Issue by Ashvala** [Ashvala/Jie#3]
Extended from #1 - The original TODO list.
- [x] Figure out a way of making the connections more secure. 
- [x] Try ascertaining how to clock things. 
- [x] potentially rewrite some of the server-side architecture better to suit development of MIDI instruments a lot better. 
- [x] create a better user interface for this.
#### BONUS:
- [x] Better name.
