### ISSUE TITLE
TODO for March 8th 2016

### ISSUE THREAD

**Issue by Ashvala** [Ashvala/Jie#6]
- [ ] Modular CsSocket
- [x] Generative client interface (look up some jsonify tricks?)
- [ ] Responsive mobile demo pages
- [x] Potential Csound for iOS demo
