### ISSUE TITLE
TODO before Senior Showcase

### ISSUE THREAD

**Issue by Ashvala** [Ashvala/Jie#9]
- [x] Interface upgrades
- [x] JavaScript timer updates
- [ ] Object sequencers to allow for chords. 
- [x] *Maintaining State for channel messages on the server side. * (**THIS IS THE MOST IMPORTANT THING**)

**Comment by Ashvala** [comment]
The chords won't happen in the next release, unfortunately.

**Comment by Ashvala** [comment]
Most of this is done as of the most recent commit: 9bdd175
